#!/usr/bin/env bash
#
# setup-worktree-env.sh — ワークツリー用の .env を自動生成する
#
# 使い方:
#   ./apps/shell/setup-worktree-env.sh            # カレントディレクトリから自動検出
#   ./apps/shell/setup-worktree-env.sh <name>     # 指定名でスロット計算
#
# ワークツリーの想定構成:
#   ../micro-dp/              ← メインリポジトリ（.git がディレクトリ）
#   ../micro-dp-feature-x/    ← ワークツリー（.git がファイル）
#   ../micro-dp-hotfix-123/   ← ワークツリー（.git がファイル）
#
# ワークツリーの検出:
#   .git がファイルの場合をワークツリーと判定し、
#   ディレクトリ名の "micro-dp-" プレフィックスを除いた部分をブランチ名として使用。
#   メインリポジトリの場合はオフセット 0（デフォルト）。
#
# ベースポート:
#   API=8080  Web=3000  Valkey=6379  MinIO=9000/9001
#   オフセットは slot * 100 で加算される（slot: 1-9）

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
ENV_FILE="$PROJECT_DIR/.env"

# ワークツリー名を決定
if [ $# -ge 1 ]; then
  WORKTREE_NAME="$1"
else
  # git worktree かどうかを .git ファイルの有無で判定
  if [ -f "$PROJECT_DIR/.git" ]; then
    # .git がファイル → worktree
    # ディレクトリ名: micro-dp-feature-x → ブランチ名: feature-x
    DIR_NAME="$(basename "$PROJECT_DIR")"
    WORKTREE_NAME="${DIR_NAME#micro-dp-}"
  else
    echo "INFO: メインリポジトリです。デフォルトポートを使用します。"
    echo "INFO: ワークツリー用 .env は不要です。"
    exit 0
  fi
fi

# ワークツリー名からスロット番号を計算（1-9）
# 決定的ハッシュ: 名前のバイト合計 mod 9 + 1
hash_name() {
  local name="$1"
  local sum=0
  local i
  for (( i=0; i<${#name}; i++ )); do
    local byte
    byte=$(printf '%d' "'${name:$i:1}")
    sum=$(( sum + byte ))
  done
  echo $(( sum % 9 + 1 ))
}

SLOT=$(hash_name "$WORKTREE_NAME")
OFFSET=$(( SLOT * 100 ))

# ポート計算
API_HOST_PORT=$(( 8080 + OFFSET ))
WEB_HOST_PORT=$(( 3000 + OFFSET ))
VALKEY_HOST_PORT=$(( 6379 + OFFSET ))
MINIO_API_HOST_PORT=$(( 9000 + OFFSET ))
MINIO_CONSOLE_HOST_PORT=$(( 9001 + OFFSET ))

# プロジェクト名（Docker Compose 用）
PROJECT_NAME="micro-dp-wt-${WORKTREE_NAME}"
# Docker Compose project name はアルファベット・数字・ハイフンのみ
PROJECT_NAME=$(echo "$PROJECT_NAME" | sed 's/[^a-zA-Z0-9-]/-/g')

# .env ファイル生成
cat > "$ENV_FILE" <<EOF
# Auto-generated by setup-worktree-env.sh
# Worktree: ${WORKTREE_NAME} (slot ${SLOT}, offset +${OFFSET})
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

COMPOSE_PROJECT_NAME=${PROJECT_NAME}

# === Host Ports ===
API_HOST_PORT=${API_HOST_PORT}
WEB_HOST_PORT=${WEB_HOST_PORT}
VALKEY_HOST_PORT=${VALKEY_HOST_PORT}
MINIO_API_HOST_PORT=${MINIO_API_HOST_PORT}
MINIO_CONSOLE_HOST_PORT=${MINIO_CONSOLE_HOST_PORT}

# === Backend (Go) ===
SQLITE_PATH=/data/sqlite/micro-dp.db

# === Valkey ===
VALKEY_ADDR=valkey:6379

# === MinIO ===
MINIO_ENDPOINT=minio:9000
MINIO_PRESIGN_ENDPOINT=localhost:${MINIO_API_HOST_PORT}
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=minioadmin
MINIO_BUCKET=micro-dp

# === Frontend ===
NEXT_PUBLIC_API_URL=http://localhost:${API_HOST_PORT}
EOF

echo "=== Worktree Environment Generated ==="
echo "Worktree:  ${WORKTREE_NAME}"
echo "Slot:      ${SLOT} (offset +${OFFSET})"
echo "Project:   ${PROJECT_NAME}"
echo "Env file:  ${ENV_FILE}"
echo ""
echo "Port assignments:"
echo "  API:            http://localhost:${API_HOST_PORT}"
echo "  Web:            http://localhost:${WEB_HOST_PORT}"
echo "  Valkey:         localhost:${VALKEY_HOST_PORT}"
echo "  MinIO API:      http://localhost:${MINIO_API_HOST_PORT}"
echo "  MinIO Console:  http://localhost:${MINIO_CONSOLE_HOST_PORT}"
echo ""
echo "Next steps:"
echo "  make up"
