// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for HealthResponseStatus.
const (
	Degraded HealthResponseStatus = "degraded"
	Ok       HealthResponseStatus = "ok"
)

// Defines values for JobRunStatus.
const (
	Failed  JobRunStatus = "failed"
	Queued  JobRunStatus = "queued"
	Running JobRunStatus = "running"
	Success JobRunStatus = "success"
)

// CreateJobRunRequest defines model for CreateJobRunRequest.
type CreateJobRunRequest struct {
	JobId     string `json:"job_id"`
	ProjectId string `json:"project_id"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Db     *string              `json:"db,omitempty"`
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// JobRun defines model for JobRun.
type JobRun struct {
	FinishedAt *time.Time   `json:"finished_at,omitempty"`
	Id         string       `json:"id"`
	JobId      string       `json:"job_id"`
	ProjectId  string       `json:"project_id"`
	StartedAt  *time.Time   `json:"started_at,omitempty"`
	Status     JobRunStatus `json:"status"`
	TenantId   string       `json:"tenant_id"`
}

// JobRunStatus defines model for JobRun.Status.
type JobRunStatus string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	Token string `json:"token"`
}

// MeResponse defines model for MeResponse.
type MeResponse struct {
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Tenants     []Tenant            `json:"tenants"`
	UserId      string              `json:"user_id"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	DisplayName *string             `json:"display_name,omitempty"`
	Email       openapi_types.Email `json:"email"`
	Password    string              `json:"password"`
}

// RegisterResponse defines model for RegisterResponse.
type RegisterResponse struct {
	TenantId string `json:"tenant_id"`
	UserId   string `json:"user_id"`
}

// Tenant defines model for Tenant.
type Tenant struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// XTenantID defines model for XTenantID.
type XTenantID = string

// ListJobRunsParams defines parameters for ListJobRuns.
type ListJobRunsParams struct {
	Limit     *int      `form:"limit,omitempty" json:"limit,omitempty"`
	XTenantID XTenantID `json:"X-Tenant-ID"`
}

// CreateJobRunParams defines parameters for CreateJobRun.
type CreateJobRunParams struct {
	XTenantID XTenantID `json:"X-Tenant-ID"`
}

// GetJobRunParams defines parameters for GetJobRun.
type GetJobRunParams struct {
	XTenantID XTenantID `json:"X-Tenant-ID"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// CreateJobRunJSONRequestBody defines body for CreateJobRun for application/json ContentType.
type CreateJobRunJSONRequestBody = CreateJobRunRequest
