/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register user */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user profile */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Start Google OAuth login */
        get: operations["startGoogleOAuth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Handle Google OAuth callback */
        get: operations["callbackGoogleOAuth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest event */
        post: operations["ingestEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Event counts summary */
        get: operations["getEventsSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tenants (superadmin only) */
        get: operations["adminListTenants"];
        put?: never;
        /** Create tenant (superadmin only) */
        post: operations["adminCreateTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tenants/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update tenant (superadmin only) */
        patch: operations["adminUpdateTenant"];
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List jobs */
        get: operations["listJobs"];
        put?: never;
        /** Create job */
        post: operations["createJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get job */
        get: operations["getJob"];
        /** Update job */
        put: operations["updateJob"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List job versions */
        get: operations["listJobVersions"];
        put?: never;
        /** Create job version (with modules and edges) */
        post: operations["createJobVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get job version detail (with modules and edges) */
        get: operations["getJobVersionDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/versions/{version_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish job version */
        post: operations["publishJobVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/job_runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List job runs */
        get: operations["listJobRuns"];
        put?: never;
        /** Create job run */
        post: operations["createJobRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/job_runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get job run by ID */
        get: operations["getJobRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/job_runs/{job_run_id}/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List modules for a job run */
        get: operations["listJobRunModules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/job_runs/{job_run_id}/modules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get job run module detail */
        get: operations["getJobRunModule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/job_runs/{job_run_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List artifacts for a job run */
        get: operations["listJobRunArtifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/job_runs/{job_run_id}/artifacts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get job run artifact detail */
        get: operations["getJobRunArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/module_types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List module types */
        get: operations["listModuleTypes"];
        put?: never;
        /** Create module type */
        post: operations["createModuleType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/module_types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get module type */
        get: operations["getModuleType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/module_types/{id}/schemas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List module type schema versions */
        get: operations["listModuleTypeSchemas"];
        put?: never;
        /** Create module type schema version */
        post: operations["createModuleTypeSchema"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List connections */
        get: operations["listConnections"];
        put?: never;
        /** Create connection */
        post: operations["createConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connections/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get connection */
        get: operations["getConnection"];
        /** Update connection */
        put: operations["updateConnection"];
        post?: never;
        /** Delete connection */
        delete: operations["deleteConnection"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List datasets */
        get: operations["listDatasets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get dataset */
        get: operations["getDataset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request presigned upload URLs */
        post: operations["createUploadPresign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark upload complete */
        post: operations["completeUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok" | "degraded";
            db?: string;
        };
        ErrorResponse: {
            error: string;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            display_name?: string;
        };
        RegisterResponse: {
            user_id: string;
            tenant_id: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginResponse: {
            token: string;
        };
        MeResponse: {
            user_id: string;
            /** Format: email */
            email: string;
            display_name: string;
            /** @enum {string} */
            platform_role: "user" | "superadmin";
            tenants: components["schemas"]["Tenant"][];
        };
        Tenant: {
            id: string;
            name: string;
            is_active: boolean;
        };
        AdminCreateTenantRequest: {
            name: string;
        };
        AdminUpdateTenantRequest: {
            name?: string;
            is_active?: boolean;
        };
        IngestEventRequest: {
            event_id: string;
            event_name: string;
            properties?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            event_time: string;
        };
        IngestEventResponse: {
            event_id: string;
            /** @enum {string} */
            status: "accepted";
        };
        EventsSummaryResponse: {
            counts: components["schemas"]["EventCount"][];
            /** Format: int64 */
            total: number;
        };
        EventCount: {
            event_name: string;
            /** Format: int64 */
            count: number;
        };
        Job: {
            id: string;
            tenant_id: string;
            name: string;
            slug: string;
            description?: string;
            is_active: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        CreateJobRequest: {
            name: string;
            slug: string;
            description?: string;
        };
        UpdateJobRequest: {
            name: string;
            slug: string;
            description?: string;
            is_active: boolean;
        };
        JobVersion: {
            id: string;
            tenant_id: string;
            job_id: string;
            version: number;
            /** @enum {string} */
            status: "draft" | "published";
            /** Format: date-time */
            published_at?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        JobVersionDetail: {
            version: components["schemas"]["JobVersion"];
            modules: components["schemas"]["JobModule"][];
            edges: components["schemas"]["JobModuleEdge"][];
        };
        CreateJobVersionRequest: {
            modules: components["schemas"]["CreateJobModuleInput"][];
            edges?: components["schemas"]["CreateEdgeInput"][];
        };
        CreateJobModuleInput: {
            module_type_id: string;
            module_type_schema_id?: string;
            connection_id?: string;
            name: string;
            config_json?: string;
            position_x?: number;
            position_y?: number;
        };
        CreateEdgeInput: {
            source_module_index: number;
            target_module_index: number;
        };
        JobModule: {
            id: string;
            tenant_id: string;
            job_version_id: string;
            module_type_id: string;
            module_type_schema_id?: string;
            connection_id?: string;
            name: string;
            config_json?: string;
            position_x?: number;
            position_y?: number;
        };
        JobModuleEdge: {
            id: string;
            tenant_id: string;
            job_version_id: string;
            source_module_id: string;
            target_module_id: string;
        };
        CreateJobRunRequest: {
            job_id: string;
            job_version_id?: string;
        };
        JobRun: {
            id: string;
            tenant_id: string;
            job_id: string;
            job_version_id?: string;
            status: components["schemas"]["JobRunStatus"];
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            finished_at?: string;
        };
        /** @enum {string} */
        JobRunStatus: "queued" | "running" | "success" | "failed" | "canceled";
        JobRunModule: {
            id: string;
            tenant_id: string;
            job_run_id: string;
            job_module_id: string;
            status: components["schemas"]["JobRunModuleStatus"];
            attempt: number;
            input_json?: string;
            output_json?: string;
            metrics_json?: string;
            error_code?: string;
            error_message?: string;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            finished_at?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        /** @enum {string} */
        JobRunModuleStatus: "queued" | "running" | "success" | "failed" | "canceled";
        JobRunArtifact: {
            id: string;
            tenant_id: string;
            job_run_id: string;
            job_run_module_id?: string;
            name: string;
            artifact_type: string;
            storage_type: string;
            storage_path: string;
            uri?: string;
            /** Format: int64 */
            size_bytes: number;
            content_type: string;
            checksum?: string;
            metadata_json?: string;
            /** Format: date-time */
            created_at?: string;
        };
        ModuleType: {
            id: string;
            tenant_id: string;
            name: string;
            /** @enum {string} */
            category: "source" | "transform" | "destination";
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        CreateModuleTypeRequest: {
            name: string;
            /** @enum {string} */
            category: "source" | "transform" | "destination";
        };
        ModuleTypeSchema: {
            id: string;
            tenant_id: string;
            module_type_id: string;
            version: number;
            json_schema: string;
            /** Format: date-time */
            created_at?: string;
        };
        CreateModuleTypeSchemaRequest: {
            json_schema: string;
        };
        Connection: {
            id: string;
            tenant_id: string;
            name: string;
            type: string;
            config_json?: string;
            secret_ref?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        CreateConnectionRequest: {
            name: string;
            type: string;
            config_json?: string;
            secret_ref?: string;
        };
        UpdateConnectionRequest: {
            name: string;
            type: string;
            config_json?: string;
            secret_ref?: string;
        };
        Dataset: {
            id: string;
            tenant_id: string;
            name: string;
            source_type: components["schemas"]["DatasetSourceType"];
            schema_json?: string;
            /** Format: int64 */
            row_count?: number;
            storage_path: string;
            /** Format: date-time */
            last_updated_at?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        /** @enum {string} */
        DatasetSourceType: "tracker" | "parquet" | "import";
        /** @enum {string} */
        UploadStatus: "presigned" | "uploaded";
        UploadFileInput: {
            filename: string;
            content_type: string;
            /** Format: int64 */
            size_bytes: number;
        };
        CreateUploadPresignRequest: {
            files: components["schemas"]["UploadFileInput"][];
        };
        UploadFilePresigned: {
            file_id: string;
            filename: string;
            presigned_url: string;
            object_key: string;
            /** Format: date-time */
            expires_at?: string;
        };
        CreateUploadPresignResponse: {
            upload_id: string;
            files: components["schemas"]["UploadFilePresigned"][];
        };
        UploadFile: {
            id: string;
            upload_id: string;
            file_name: string;
            object_key: string;
            content_type: string;
            /** Format: int64 */
            size_bytes: number;
            /** Format: date-time */
            created_at?: string;
        };
        Upload: {
            id: string;
            tenant_id: string;
            status: components["schemas"]["UploadStatus"];
            files: components["schemas"]["UploadFile"][];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
    };
    responses: {
        /** @description Error response */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        XTenantID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Logged in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            401: components["responses"]["ErrorResponse"];
        };
    };
    startGoogleOAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to Google OAuth consent page */
            302: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["ErrorResponse"];
        };
    };
    callbackGoogleOAuth: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to app after login attempt */
            302: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            500: components["responses"]["ErrorResponse"];
        };
    };
    ingestEvent: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": components["parameters"]["XTenantID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestEventRequest"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestEventResponse"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    getEventsSummary: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": components["parameters"]["XTenantID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event counts summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsSummaryResponse"];
                };
            };
            401: components["responses"]["ErrorResponse"];
        };
    };
    adminListTenants: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of tenants */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Tenant"][];
                    };
                };
            };
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
        };
    };
    adminCreateTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminCreateTenantRequest"];
            };
        };
        responses: {
            /** @description Created tenant */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
        };
    };
    adminUpdateTenant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUpdateTenantRequest"];
            };
        };
        responses: {
            /** @description Updated tenant */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
        };
    };
    listJobs: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": components["parameters"]["XTenantID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of jobs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Job"][];
                    };
                };
            };
            401: components["responses"]["ErrorResponse"];
        };
    };
    createJob: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": components["parameters"]["XTenantID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobRequest"];
            };
        };
        responses: {
            /** @description Created job */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": components["parameters"]["XTenantID"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            401: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
        };
    };
    updateJob: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": components["parameters"]["XTenantID"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateJobRequest"];
            };
        };
        responses: {
            /** @description Updated job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    listJobVersions: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": components["parameters"]["XTenantID"];
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of job versions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["JobVersion"][];
                    };
                };
            };
            401: components["responses"]["ErrorResponse"];
        };
    };
    createJobVersion: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": components["parameters"]["XTenantID"];
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobVersionRequest"];
            };
        };
        responses: {
            /** @description Created job version */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobVersion"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
        };
    };
    getJobVersionDetail: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": components["parameters"]["XTenantID"];
            };
            path: {
                job_id: string;
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job version detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobVersionDetail"];
                };
            };
            401: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
        };
    };
    publishJobVersion: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": components["parameters"]["XTenantID"];
            };
            path: {
                job_id: string;
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published job version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobVersion"];
                };
            };
            401: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    listJobRuns: {
        parameters: {
            query?: {
                limit?: number;
            };
            header: {
                "X-Tenant-ID": components["parameters"]["XTenantID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of job runs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["JobRun"][];
                    };
                };
            };
            401: components["responses"]["ErrorResponse"];
        };
    };
    createJobRun: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": components["parameters"]["XTenantID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobRunRequest"];
            };
        };
        responses: {
            /** @description Created job run */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRun"];
                };
            };
            401: components["responses"]["ErrorResponse"];
        };
    };
    getJobRun: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": components["parameters"]["XTenantID"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job run detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRun"];
                };
            };
            401: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
        };
    };
    listJobRunModules: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": components["parameters"]["XTenantID"];
            };
            path: {
                job_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of job run modules */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["JobRunModule"][];
                    };
                };
            };
            401: components["responses"]["ErrorResponse"];
        };
    };
    getJobRunModule: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": components["parameters"]["XTenantID"];
            };
            path: {
                job_run_id: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job run module detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRunModule"];
                };
            };
            401: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
        };
    };
    listJobRunArtifacts: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": components["parameters"]["XTenantID"];
            };
            path: {
                job_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of job run artifacts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["JobRunArtifact"][];
                    };
                };
            };
            401: components["responses"]["ErrorResponse"];
        };
    };
    getJobRunArtifact: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": components["parameters"]["XTenantID"];
            };
            path: {
                job_run_id: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job run artifact detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRunArtifact"];
                };
            };
            401: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
        };
    };
    listModuleTypes: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": components["parameters"]["XTenantID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of module types */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ModuleType"][];
                    };
                };
            };
            401: components["responses"]["ErrorResponse"];
        };
    };
    createModuleType: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": components["parameters"]["XTenantID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateModuleTypeRequest"];
            };
        };
        responses: {
            /** @description Created module type */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleType"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    getModuleType: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": components["parameters"]["XTenantID"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Module type detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleType"];
                };
            };
            401: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
        };
    };
    listModuleTypeSchemas: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": components["parameters"]["XTenantID"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of module type schemas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ModuleTypeSchema"][];
                    };
                };
            };
            401: components["responses"]["ErrorResponse"];
        };
    };
    createModuleTypeSchema: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": components["parameters"]["XTenantID"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateModuleTypeSchemaRequest"];
            };
        };
        responses: {
            /** @description Created module type schema */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleTypeSchema"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
        };
    };
    listConnections: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": components["parameters"]["XTenantID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of connections */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Connection"][];
                    };
                };
            };
            401: components["responses"]["ErrorResponse"];
        };
    };
    createConnection: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": components["parameters"]["XTenantID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConnectionRequest"];
            };
        };
        responses: {
            /** @description Created connection */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Connection"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    getConnection: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": components["parameters"]["XTenantID"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connection detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Connection"];
                };
            };
            401: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
        };
    };
    updateConnection: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": components["parameters"]["XTenantID"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateConnectionRequest"];
            };
        };
        responses: {
            /** @description Updated connection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Connection"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    deleteConnection: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": components["parameters"]["XTenantID"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
        };
    };
    listDatasets: {
        parameters: {
            query?: {
                q?: string;
                source_type?: components["schemas"]["DatasetSourceType"];
                limit?: number;
                offset?: number;
            };
            header: {
                "X-Tenant-ID": components["parameters"]["XTenantID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of datasets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Dataset"][];
                    };
                };
            };
            401: components["responses"]["ErrorResponse"];
        };
    };
    getDataset: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": components["parameters"]["XTenantID"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dataset detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dataset"];
                };
            };
            401: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
        };
    };
    createUploadPresign: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": components["parameters"]["XTenantID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUploadPresignRequest"];
            };
        };
        responses: {
            /** @description Presigned URLs created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateUploadPresignResponse"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
        };
    };
    completeUpload: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": components["parameters"]["XTenantID"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upload completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Upload"];
                };
            };
            401: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
}
