FROM golang:1.26-alpine

RUN go install github.com/air-verse/air@latest

WORKDIR /app
COPY apps/golang/backend/go.mod apps/golang/backend/go.sum ./
RUN go mod download

COPY apps/golang/backend/ .
RUN mkdir -p /data/sqlite

ENTRYPOINT ["air"]
